name: SSH proxy command

on:
  push:
    branches:
      - main

jobs:
  ssh-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Connect via SSH using Proxy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          proxy_host: ${{ secrets.PROXY_HOST }}
          proxy_username: ${{ secrets.PROXY_USERNAME }}
          proxy_key: ${{ secrets.PROXY_KEY }}
          proxy_port: ${{ secrets.PROXY_PORT }}
          script: |
            mkdir -p abc/def
            ls -al
